include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  DS_DISABLE_DIND: "true"

stages:
  - build
  - test
  - release

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  image: gradle:6.5
  stage: build
  script:
    - gradle clean build

release:
  only:
    - master
  image: gradle:6.5
  stage: release
  script:
    - gradle publish
