include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - release

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  image: gradle:6.5
  stage: build
  script:
    - gradle clean build

release:
  image: gradle:6.5
  stage: release
  script:
    - gradle publish
